/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CareerTimeline: typeof import('./src/components/Content/CareerTimeline.vue')['default']
    CommonIcon: typeof import('./src/components/Common/CommonIcon.vue')['default']
    CommonImage: typeof import('./src/components/Common/CommonImage.vue')['default']
    CopyCheckIcon: typeof import('./src/components/Common/CopyCheckIcon.vue')['default']
    CustomButton: typeof import('./src/components/Common/CustomButton.vue')['default']
    CustomSvg: typeof import('./src/components/Common/CustomSvg.vue')['default']
    Divider: typeof import('./src/components/Common/Divider.vue')['default']
    ExperimentList: typeof import('./src/components/Content/ExperimentList.vue')['default']
    GithubSvg: typeof import('./src/components/Common/GithubSvg.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MyStack: typeof import('./src/components/Content/MyStack.vue')['default']
    NavigationDesktop: typeof import('./src/components/Navigation/NavigationDesktop.vue')['default']
    NavigationMobile: typeof import('./src/components/Navigation/NavigationMobile.vue')['default']
    NavigationRoot: typeof import('./src/components/Navigation/NavigationRoot.vue')['default']
    Profile: typeof import('./src/components/Content/Profile.vue')['default']
    ProjectList: typeof import('./src/components/Content/ProjectList.vue')['default']
  }
}
