/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CareerTimeline: typeof import('./src/components/Content/CareerTimeline.vue')['default']
    CommonButton: typeof import('./src/components/Common/CommonButton.vue')['default']
    CommonCard: typeof import('./src/components/Common/CommonCard.vue')['default']
    CommonDropdown: typeof import('./src/components/Common/CommonDropdown.vue')['default']
    CommonImage: typeof import('./src/components/Common/CommonImage.vue')['default']
    CommonModal: typeof import('./src/components/Common/CommonModal.vue')['default']
    CopyCheckIcon: typeof import('./src/components/Common/CopyCheckIcon.vue')['default']
    Divider: typeof import('./src/components/Common/Divider.vue')['default']
    ExperimentList: typeof import('./src/components/Content/ExperimentList.vue')['default']
    GithubSvg: typeof import('./src/components/Common/GithubSvg.vue')['default']
    MyStack: typeof import('./src/components/Content/MyStack.vue')['default']
    NavigationDesktop: typeof import('./src/components/Navigation/NavigationDesktop.vue')['default']
    NavigationMobile: typeof import('./src/components/Navigation/NavigationMobile.vue')['default']
    NavigationRoot: typeof import('./src/components/Navigation/NavigationRoot.vue')['default']
    Profile: typeof import('./src/components/Content/Profile.vue')['default']
    ProjectList: typeof import('./src/components/Content/ProjectList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
